/**
 * Auto-generated by `scripts/embed-play-templates.ts`.
 *
 * This file intentionally inlines the locally copied Play templates so
 * `bags-cli` can scaffold projects without reaching back into the Play
 * monorepo at runtime.
 */
/** biome-ignore-all lint/suspicious/noTemplateCurlyInString: to be determined */

export const EMBEDDED_TEMPLATES: ReadonlyMap<string, string> = new Map([
	[
		"app/base/app.ts.tmpl",
		'import { createActionNode, cronTrigger, defineApp, expr } from "@bagsfm/play-sdk";\n\nconst logStart = createActionNode("log-start", "core", "log")\n  .config({\n    message: expr.concat("Running {{APP_DISPLAY_NAME}} — scaffolded with bags init"),\n    level: "info",\n  })\n  .build();\n\nconst saveState = createActionNode("save-state", "core", "state-set")\n  .config({\n    key: "lastRun",\n    value: expr.node("log-start", "timestamp"),\n  })\n  .build();\n\nexport default defineApp("{{APP_NAME}}", "{{APP_DISPLAY_NAME}}")\n  .version("1.0.0")\n  .description("Scaffolded with bags init.")\n  .trigger(cronTrigger("0 * * * *"))\n  .node(logStart)\n  .node(saveState)\n  .connect("log-start", "save-state")\n  .build();\n',
	],
	[
		"app/base/bags.toml",
		'entry = "app.ts"\nruntime = "bun"\npackage_manager = "bun"\n',
	],
	["app/base/gitignore", "node_modules/\nrelease/\n.env\n.env.local\n"],
	[
		"app/base/package.json",
		'{\n  "name": "{{APP_NAME}}",\n  "version": "1.0.0",\n  "description": "Bags Play App scaffolded with bags init",\n  "private": true,\n  "type": "module",\n  "scripts": {\n    "build": "bags play build",\n    "test": "bun test"\n  },\n  "dependencies": {\n    "@bagsfm/play-bags-plugin": "latest",\n    "@bagsfm/play-sdk": "{{PLAY_SDK_VERSION}}"\n  },\n  "devDependencies": {\n    "@types/bun": "{{BUN_TYPES_VERSION}}",\n    "typescript": "{{TYPESCRIPT_VERSION}}"\n  }\n}\n',
	],
	[
		"app/base/tsconfig.json",
		'{\n\t"compilerOptions": {\n\t\t"module": "ESNext",\n\t\t"moduleResolution": "bundler",\n\t\t"noEmit": true,\n\t\t"skipLibCheck": true,\n\t\t"strict": true,\n\t\t"target": "ESNext"\n\t},\n\t"include": ["*.ts", "test/**/*.ts"]\n}\n',
	],
	[
		"app/with-tests/test/app.test.ts.tmpl",
		'import { describe, expect, test } from "bun:test";\nimport { validateApp } from "@bagsfm/play-sdk";\nimport app from "../app";\n\ndescribe("app scaffold", () => {\n  test("exports a valid AppDefinition", () => {\n    expect(validateApp(app)).toEqual([]);\n  });\n\n  test("has version set", () => {\n    expect(app.version).toBe("1.0.0");\n  });\n\n  test("has correct trigger type", () => {\n    expect(app.trigger.type).toBe("cron");\n  });\n\n  test("has expected nodes", () => {\n    expect(app.nodes).toHaveLength(2);\n    expect(app.nodes.map((n) => n.id)).toEqual(["log-start", "save-state"]);\n  });\n\n  test("has expected edges", () => {\n    expect(app.edges).toHaveLength(1);\n    expect(app.edges[0]).toMatchObject({ source: "log-start", target: "save-state" });\n  });\n});\n',
	],
	[
		"app/with-tests/tsconfig.test.json",
		'{\n\t"extends": "./tsconfig.json",\n\t"compilerOptions": {\n\t\t"types": ["bun-types"]\n\t},\n\t"include": ["test/**/*.ts", "*.ts"]\n}\n',
	],
	[
		"plugin/base/gitignore",
		"node_modules/\ndist/\ncoverage/\n.turbo/\n*.tsbuildinfo\n",
	],
	[
		"plugin/base/package.json",
		'{\n  "name": "{{PLUGIN_PACKAGE_NAME}}",\n  "version": "0.0.1",\n  "description": "{{PLUGIN_DESCRIPTION}}",\n  "type": "module",\n  "main": "./src/plugin.ts",\n  "types": "./src/plugin.ts",\n  "exports": {\n    ".": {\n      "bun": "./src/plugin.ts",\n      "types": "./src/plugin.ts",\n      "import": "./dist/plugin.js"\n    }\n  },\n  "license": "MIT",\n  "scripts": {\n    "build": "tsc --noEmit",\n    "test": "bun test",\n    "typecheck": "tsc --noEmit",\n    "lint": "biome check .",\n    "lint:fix": "biome check --write .",\n    "format": "biome check --write ."\n  },\n  "peerDependencies": {\n    "@bagsfm/play-sdk": "{{PLAY_SDK_VERSION}}"\n  },\n  "devDependencies": {\n    "@bagsfm/play-sdk": "{{PLAY_SDK_VERSION}}",\n    "@bagsfm/play-shared": "{{PLAY_SDK_VERSION}}",\n    "@types/bun": "{{BUN_TYPES_VERSION}}",\n    "typescript": "{{TYPESCRIPT_VERSION}}",\n    "zod": "^4.0.0",\n    "effect": "^3.0.0"\n  }\n}\n',
	],
	[
		"plugin/base/src/actions/example.ts.tmpl",
		'/**\n * Example action for the {{PLUGIN_NAME}} plugin.\n *\n * Replace this with your actual action implementation.\n *\n * @packageDocumentation\n */\n\nimport { defineAction } from "@bagsfm/play-sdk";\nimport { Effect } from "effect";\nimport { z } from "zod";\n\nexport const exampleAction = defineAction("example", "Example Action")\n  .description("An example action — replace with your implementation")\n  .config(\n    z.object({\n      message: z.string().describe("A message to process"),\n    })\n  )\n  // Optional: charge native SOL per run of this action (treasury + fixed lamports or dynamic compute)\n  // .fee({ treasury: "YourSolanaTreasuryAddressHere11111111111111111111", lamports: 1_000_000n })\n  .output(\n    z.object({\n      result: z.string().describe("The processed result"),\n    })\n  )\n  .execute((input) =>\n    Effect.succeed({\n      data: { result: `Processed: ${input.config.message}` },\n    })\n  );\n',
	],
	[
		"plugin/base/src/plugin.ts.tmpl",
		'/**\n * {{PLUGIN_NAME}} plugin for Bags Play.\n *\n * @packageDocumentation\n */\n\nimport {\n  createActionFactories,\n  createPluginConfigAccessor,\n  createPluginManifest,\n  definePlugin,\n} from "@bagsfm/play-sdk";\nimport { z } from "zod";\nimport { exampleAction } from "./actions/example";\n\n/**\n * Plugin-level config schema.\n * Define any API keys or settings your plugin needs here.\n */\nexport const configSchema = z.object({\n  apiKey: z.string().describe("API key for the external service"),\n});\n\n/** TypeScript type for the plugin config. */\nexport type {{PLUGIN_CONFIG_TYPE}} = z.infer<typeof configSchema>;\n\n/** Typed config accessor for action execute functions. */\nexport const useConfig = createPluginConfigAccessor(configSchema);\n\n/** Runtime plugin object. */\nexport const plugin = definePlugin("{{PLUGIN_ID}}", "{{PLUGIN_NAME}}")\n  .version("0.0.1")\n  .author("{{PLUGIN_AUTHOR}}")\n  .description("{{PLUGIN_DESCRIPTION}}")\n  .category("{{PLUGIN_CATEGORY}}")\n  .engines({ schema: "1.0.0" })\n  .configSchema(configSchema)\n  // Optional: plugin-scoped secrets (create with `bags secrets create NAME --plugin {{PLUGIN_ID}}`)\n  // .secrets({ apiKey: { secretId: "sec_xxx", overridable: true } })\n  .actions([exampleAction])\n  .build();\n\n/** Serializable manifest for the registry. */\nexport const manifest = createPluginManifest(plugin);\n\n/** Typed action node factories for app developers. */\nexport const actions = createActionFactories("{{PLUGIN_ID}}", {\n  example: exampleAction,\n});\n',
	],
	[
		"plugin/base/test/plugin.test.ts.tmpl",
		'import { describe, expect, test } from "bun:test";\nimport { testPlugin } from "@bagsfm/play-sdk";\nimport { actions, manifest, plugin } from "../src/plugin";\n\ndescribe("{{PLUGIN_NAME}} plugin", () => {\n  test("plugin has correct metadata", () => {\n    expect(plugin.metadata.id).toBe("{{PLUGIN_ID}}");\n    expect(plugin.metadata.name).toBe("{{PLUGIN_NAME}}");\n  });\n\n  test("testPlugin validation returns no errors", () => {\n    const issues = testPlugin(plugin);\n    const errors = issues.filter((i) => i.type === "error");\n    expect(errors).toHaveLength(0);\n  });\n\n  test("manifest is valid", () => {\n    expect(manifest.pluginId).toBe("{{PLUGIN_ID}}");\n    expect(manifest.actions.length).toBeGreaterThan(0);\n  });\n\n  test("typed action factories exist", () => {\n    expect(typeof actions.example).toBe("function");\n  });\n\n  test("typed factory produces correct node shape", () => {\n    const node = actions.example("my-node")\n      .config({ message: "hello" })\n      .build();\n    expect(node.pluginId).toBe("{{PLUGIN_ID}}");\n    expect(node.actionId).toBe("example");\n  });\n});\n',
	],
	[
		"plugin/base/tsconfig.json",
		'{\n\t"compilerOptions": {\n\t\t"target": "ESNext",\n\t\t"module": "ESNext",\n\t\t"moduleResolution": "bundler",\n\t\t"strict": true,\n\t\t"noEmit": true,\n\t\t"esModuleInterop": true,\n\t\t"skipLibCheck": true,\n\t\t"forceConsistentCasingInFileNames": true,\n\t\t"resolveJsonModule": true,\n\t\t"isolatedModules": true\n\t},\n\t"include": ["src/**/*.ts", "test/**/*.ts"]\n}\n',
	],
]);

export const EMBEDDED_PLAY_SDK_VERSION = "^0.0.42";
