import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, posix, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(scriptDirectory, "..");
const templateSourceDirectory = resolve(
	repositoryRoot,
	"src/play/templates/source",
);
const outputPath = resolve(repositoryRoot, "src/play/templates/embedded.ts");

interface BagsCliPackageJson {
	dependencies?: Record<string, string | undefined>;
}

interface PlaySdkPackageJson {
	version?: unknown;
}

const collectTemplateFilePaths = async (
	directory: string,
): Promise<string[]> => {
	const entries = await readdir(directory, { withFileTypes: true });
	const filePaths: string[] = [];

	for (const entry of entries.toSorted((left, right) =>
		left.name.localeCompare(right.name),
	)) {
		const entryPath = resolve(directory, entry.name);

		if (entry.isDirectory()) {
			filePaths.push(...(await collectTemplateFilePaths(entryPath)));
			continue;
		}

		filePaths.push(entryPath);
	}

	return filePaths;
};

const renderEmbeddedTemplatesModule = (
	entries: ReadonlyArray<readonly [string, string]>,
	playSdkVersion: string,
): string => {
	const renderedEntries = entries
		.map(
			([relativePath, contents]) =>
				`  [${JSON.stringify(relativePath)}, ${JSON.stringify(contents)}],`,
		)
		.join("\n");

	return `/**
 * Auto-generated by \`scripts/embed-play-templates.ts\`.
 *
 * This file intentionally inlines the locally copied Play templates so
 * \`bags-cli\` can scaffold projects without reaching back into the Play
 * monorepo at runtime.
 */

export const EMBEDDED_TEMPLATES: ReadonlyMap<string, string> = new Map([
${renderedEntries}
]);

export const EMBEDDED_PLAY_SDK_VERSION = ${JSON.stringify(playSdkVersion)};
`;
};

const resolvePlaySdkTemplateVersion = async (): Promise<string> => {
	const bagsCliPackageJson = JSON.parse(
		await readFile(resolve(repositoryRoot, "package.json"), "utf8"),
	) as BagsCliPackageJson;
	const dependencyVersion =
		bagsCliPackageJson.dependencies?.["@bagsfm/play-sdk"];

	if (!dependencyVersion) {
		throw new Error("Missing @bagsfm/play-sdk dependency in package.json.");
	}

	if (!dependencyVersion.startsWith("file:")) {
		return dependencyVersion;
	}

	const relativePackagePath = dependencyVersion.slice("file:".length);
	const playSdkPackageJson = JSON.parse(
		await readFile(
			resolve(repositoryRoot, relativePackagePath, "package.json"),
			"utf8",
		),
	) as PlaySdkPackageJson;

	if (
		typeof playSdkPackageJson.version !== "string" ||
		playSdkPackageJson.version.length === 0
	) {
		throw new Error(
			`Missing version in ${relativePackagePath}/package.json for @bagsfm/play-sdk.`,
		);
	}

	return `^${playSdkPackageJson.version}`;
};

const main = async (): Promise<void> => {
	const templateFilePaths = await collectTemplateFilePaths(
		templateSourceDirectory,
	);
	if (templateFilePaths.length === 0) {
		throw new Error(
			`No template files found under ${relative(repositoryRoot, templateSourceDirectory)}.`,
		);
	}

	const entries = await Promise.all(
		templateFilePaths.map(async (templateFilePath) => {
			const relativePath = posix.join(
				...relative(templateSourceDirectory, templateFilePath).split(/[/\\]+/),
			);
			const contents = await readFile(templateFilePath, "utf8");
			return [relativePath, contents] as const;
		}),
	);
	const playSdkVersion = await resolvePlaySdkTemplateVersion();

	await mkdir(dirname(outputPath), { recursive: true });
	await writeFile(
		outputPath,
		renderEmbeddedTemplatesModule(entries, playSdkVersion),
		"utf8",
	);
	console.log(
		`Embedded ${entries.length} Play templates into ${relative(repositoryRoot, outputPath)}.`,
	);
};

void main();
